#ifndef _INSTRUCTION_LIST_H_
#define _INSTRUCTION_LIST_H_

#include "instructionCPP.h"
#include <list>

using namespace std;

class instruction_list{

private:
    list<instruction*> lista;
    unsigned int count;

public:
    instruction_list(void);

    void add (instruction *i);

    unsigned int length (void);

    void std_out_print (unsigned int times);

    instruction *nth_item(unsigned int n);

    list<instruction*> get_list(void);

};
#endif
